[[redirects]]
  from = "/api/*"
  to = "http://18.226.165.214/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
# Importante: Configurar headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"